### ISSUE TITLE
Changes to the footer and its links

### ISSUE THREAD

**Issue by Petrosdevri** [GDSC-IIIT-Kalyani/Hacktober-Fest-2023#14]
The page looks awesome so far but there are some further details we can look after in order to improve it. I want to pay special attention to the footer:
- Update the media links with a hover effect to offer a dynamic experience to the user. The colour could be a gold variant like the one of the borders.
- **OPTIONAL:** Create some logos for the *Share* and *Follow* sections based on the ones in the rest of the page. I am not completely sure how to achieve that so I would like to know what kind of tools you used to create the logos but I have some experience with logo creation. Of course, this is something optional and therefore not my priority.

I am open to your advice and feedback in the replies.

**Comment by Wafmulla** [comment]
Hello can you assign this issue to me under Hacktoberfest 2023 label?
