### ISSUE TITLE
Change the font in the FAQ accordion

### ISSUE THREAD

**Issue by Petrosdevri** [GDSC-IIIT-Kalyani/Hacktober-Fest-2023#7]
I think that the answers in the FAQ accordion need to have a font which matches rest of the page.

**Comment by bhaskar1001101** [comment]
@Petrosdevri We're using the Jetbrains Mono font for the entire website. But it does feel a bit out of place. What are your proposed changes?

**Comment by Petrosdevri** [comment]
@bhaskar1001101 well never mind, I just saw the font of the answers in the FAQ section looked different in one of my computers compared to what I expected. But it's displayed properly in my PC so that's fine. I will therefore close that issue and propose something else.
